"""
app.py — Web Application for AI-Generated Image Detection
==========================================================
Deployed on Hugging Face Spaces using Gradio.
Run locally: python app.py
"""

import gradio as gr
import torch
import torch.nn.functional as F
from PIL import Image
from torchvision import transforms
import numpy as np

# ── Model (same as model.py but self-contained for HF Spaces) ────────────────

class CLIPBackbone(torch.nn.Module):
    EMBED_DIM = 768
    def __init__(self):
        super().__init__()
        import open_clip
        model, _, _ = open_clip.create_model_and_transforms("ViT-L-14", pretrained="openai")
        self.visual = model.visual
        for p in self.visual.parameters():
            p.requires_grad = False
        self.visual.eval()

    def train(self, mode=True):
        super().train(mode); self.visual.eval(); return self

    def forward(self, x):
        with torch.no_grad():
            feats = self.visual(x)
        return F.normalize(feats, dim=-1)


class LinearProbingDetector(torch.nn.Module):
    def __init__(self, embed_dim=768, dropout=0.2):
        super().__init__()
        self.backbone = CLIPBackbone()
        self.head = torch.nn.Sequential(
            torch.nn.Dropout(p=dropout),
            torch.nn.Linear(embed_dim, 1, bias=True),
        )

    def forward(self, x):
        return self.head(self.backbone(x))

    def predict_proba(self, x):
        return torch.sigmoid(self.forward(x)).squeeze(1)


# ── Load model ────────────────────────────────────────────────────────────────

TRANSFORM = transforms.Compose([
    transforms.Resize((224, 224)),
    transforms.ToTensor(),
    transforms.Normalize(mean=(0.485, 0.456, 0.406),
                         std=(0.229, 0.224, 0.225)),
])

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model  = None

def load_model():
    global model
    if model is not None:
        return
    print("Loading model...")
    model = LinearProbingDetector().to(device)
    try:
        ckpt = torch.load("checkpoints/best.pt", map_location=device, weights_only=False)
        model.load_state_dict(ckpt["model_state"])
        print("✓ Checkpoint loaded")
    except FileNotFoundError:
        print("⚠ No checkpoint found — using random weights (for demo only)")
    model.eval()


# ── Inference ─────────────────────────────────────────────────────────────────

@torch.no_grad()
def predict(image: Image.Image):
    load_model()

    if image is None:
        return "Please upload an image.", None, None

    tensor = TRANSFORM(image.convert("RGB")).unsqueeze(0).to(device)
    prob   = model.predict_proba(tensor).item()

    label      = "🔴 FAKE (AI-Generated)" if prob >= 0.5 else "🟢 REAL (Authentic)"
    confidence = prob if prob >= 0.5 else 1 - prob
    conf_pct   = confidence * 100

    # Confidence bar data for plot
    real_pct = (1 - prob) * 100
    fake_pct = prob * 100

    details = f"""
**Result: {label}**

| Metric | Value |
|--------|-------|
| Confidence | {conf_pct:.1f}% |
| P(Fake) score | {prob:.4f} |
| P(Real) score | {1-prob:.4f} |
| Device | {str(device).upper()} |

{"⚠️ The model is fairly confident this is AI-generated." if prob > 0.8 else
 "⚠️ The model is fairly confident this is a real image." if prob < 0.2 else
 "ℹ️ The model has moderate confidence — result may be uncertain."}
"""
    return label, conf_pct, details


# ── Gradio UI ─────────────────────────────────────────────────────────────────

css = """
.gradio-container { max-width: 900px; margin: auto; font-family: Arial, sans-serif; }
.result-box { font-size: 1.4em; font-weight: bold; text-align: center; padding: 20px; border-radius: 10px; }
footer { display: none !important; }
"""

with gr.Blocks(css=css, title="AI Image Detector — CSE429") as demo:

    gr.Markdown("""
    # 🔍 AI-Generated Image Detector
    ### CSE429 — Computer Vision & Pattern Recognition | E-JUST Spring 2026
    
    Upload any image to find out if it was **generated by AI** or is a **real photograph**.
    
    Based on **UniversalFakeDetect** (Ojha et al., CVPR 2023) — uses a frozen CLIP-ViT-L/14 backbone.
    """)

    with gr.Row():
        with gr.Column(scale=1):
            image_input = gr.Image(type="pil", label="Upload Image", height=300)
            submit_btn  = gr.Button("🔍 Analyze Image", variant="primary", size="lg")

        with gr.Column(scale=1):
            result_label = gr.Textbox(label="Verdict", lines=1, interactive=False)
            confidence   = gr.Slider(minimum=0, maximum=100, label="Confidence (%)",
                                     interactive=False, value=0)
            details_box  = gr.Markdown(label="Details")

    gr.Markdown("---")

    gr.Markdown("""
    ### 📊 How it works
    1. Your image is passed through a **frozen CLIP-ViT-L/14** visual encoder (307M parameters)
    2. The 768-dimensional feature vector is fed to a **single linear layer** (only 769 trainable parameters)
    3. The output probability determines if the image is real or AI-generated
    
    ### 👥 Team
    | Name | ID | Role |
    |------|-----|------|
    | Mohamed Ahmed Mohamed Elhageen | 120220207 | Model Architecture & Implementation |
    | Youssef Ahmed Abo Wali | 120220204 | Dataset Collection & Preprocessing |
    | Belal Amr Abdelkarim | 120220168 | Training Pipeline & Optimization |
    | Mohamed Mahmoud Kotb | 120220042 | Evaluation & Results Analysis |
    | Seif Eldin Ebeid | 120220032 | Research Extension & Generalization |
    | Omar Ibrahim Abdelhamid | 120220132 | System Deployment & Web Application |
    """)

    submit_btn.click(
        fn=predict,
        inputs=[image_input],
        outputs=[result_label, confidence, details_box]
    )

    gr.Examples(
        examples=[
            ["data/processed/cifake/test/real/0.png"],
            ["data/processed/cifake/test/fake/0.png"],
        ] if __name__ == "__main__" else [],
        inputs=image_input,
    )


if __name__ == "__main__":
    demo.launch(share=True, server_port=7860)
